#!/bin/bash

# chmod +x tools/test-e2e-android

function cleanUp {
  if ps -p $(cat appium-server.pid)> /dev/null; then
    kill -KILL $(cat appium-server.pid)
  fi
  rm appium-server.pid
  rm appium.log
}

set -eEu -o pipefail
shopt -s extdebug
IFS=$'\n\t'
trap 'onFailure $?' ERR
trap cleanUp EXIT

function onFailure() {
  echo "Unhandled script error $1 at ${BASH_SOURCE[0]}:${BASH_LINENO[0]}" >&2
  exit 1
}

node ./script/bootup_android.js 
$(npm bin)/appium --port 4723 > appium.log & echo $! > appium-server.pid
sleep 5
$(npm bin)/tape android/index.js | tap-spec
